// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4JMyGXmjj2OkmxS3MSaH38kihASJ7kE',
    appId: '1:144290987788:web:f3fae067f890e40cbb5329',
    messagingSenderId: '144290987788',
    projectId: 'todo-5a0cc',
    authDomain: 'todo-5a0cc.firebaseapp.com',
    storageBucket: 'todo-5a0cc.firebasestorage.app',
    measurementId: 'G-0D1YW72P2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMhhn57la_zrpUgturekPdBd5xXwa6sU4',
    appId: '1:144290987788:android:d7974bd87c5c3ca4bb5329',
    messagingSenderId: '144290987788',
    projectId: 'todo-5a0cc',
    storageBucket: 'todo-5a0cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvd5EiTrbIfCtKUyw4Erfvmh5PCszesCg',
    appId: '1:144290987788:ios:b7bd773982be5418bb5329',
    messagingSenderId: '144290987788',
    projectId: 'todo-5a0cc',
    storageBucket: 'todo-5a0cc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvd5EiTrbIfCtKUyw4Erfvmh5PCszesCg',
    appId: '1:144290987788:ios:b7bd773982be5418bb5329',
    messagingSenderId: '144290987788',
    projectId: 'todo-5a0cc',
    storageBucket: 'todo-5a0cc.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd4JMyGXmjj2OkmxS3MSaH38kihASJ7kE',
    appId: '1:144290987788:web:6570e6c1371872aebb5329',
    messagingSenderId: '144290987788',
    projectId: 'todo-5a0cc',
    authDomain: 'todo-5a0cc.firebaseapp.com',
    storageBucket: 'todo-5a0cc.firebasestorage.app',
    measurementId: 'G-0G7DDWN424',
  );
}
